In [2]:
import torch
import torch.nn as nn

In [3]:
x=torch.ones((2,2),dtype=torch.float32)
y=torch.ones((2,2),dtype=torch.float32)*2

x=torch.tensor([[1,2],[3,4]],dtype=torch.float32).unsqueeze(0)
y=torch.tensor([[5,6],[7,18]],dtype=torch.float32).unsqueeze(0)

a=torch.stack([x,y])
print(x)
print(y)
print(a.size())

tensor([[[1., 2.],
         [3., 4.]]])
tensor([[[ 5.,  6.],
         [ 7., 18.]]])
torch.Size([2, 1, 2, 2])


In [4]:
with torch.no_grad():
    norm=nn.BatchNorm2d(num_features=1,momentum=1)  
    b=norm(a)
print(norm.running_mean,norm.running_var)

tensor([5.7500]) tensor([28.5000])


In [5]:
var=a.var([0,2,3],unbiased=False)
mean=a.mean([0,2,3])


In [6]:
(a-mean)/torch.sqrt(var)

tensor([[[[-0.9512, -0.7509],
          [-0.5507, -0.3504]]],


        [[[-0.1502,  0.0501],
          [ 0.2503,  2.4531]]]])

In [7]:
b

tensor([[[[-0.9512, -0.7509],
          [-0.5507, -0.3504]]],


        [[[-0.1502,  0.0501],
          [ 0.2503,  2.4531]]]])

In [9]:
ps=norm.named_parameters()

In [10]:
while True:
    try:
        p=next(ps)
        print(p)
    except StopIteration:
        break

('weight', Parameter containing:
tensor([1.], requires_grad=True))
('bias', Parameter containing:
tensor([0.], requires_grad=True))


In [15]:
a=torch.tensor([[1,2],[3,4]],dtype=torch.float32)
drop=nn.Dropout(0.1)
b=drop(a)
b

tensor([[1.1111, 2.2222],
        [3.3333, 4.4444]])

In [17]:
a/0.9

tensor([[1.1111, 2.2222],
        [3.3333, 4.4444]])